## RPC-based "ping" service. Request the Server to perform its
## Precompiled action --> predefined script is executed on the server
## 
RPCCLNT = sync_vault_clnt.c  
RPCHEADER = sync_vault.h  
RPCGENERATED = $(RPCCLNT) $(RPCHEADER)
RPCCLIENT = sync_vault_client.c
RPCSERVER = sync_vault_server.c
EXES = sync_vault_client sync_vault_server wait-for-file

CFLAGS =  -DSERVICE_NAME=\"sync_vault_server\"
CFLAGS += -I /usr/include/tirpc -ltirpc

default: build

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Generate the auto-created files
$(RPCCLNT): sync_vault.x
	rpcgen -N -l -o $(RPCCLNT) $^

$(RPCHEADER): sync_vault.x
	rpcgen -N -h -o $(RPCHEADER) $^ 

# Client main is also autogenerated
$(RPCCLIENT): sync_vault.x sync_vault.h
	rpcgen -Sc -N -o $@ $<

sync_vault_server: sync_vault_svc.o sync_vault_server.o $(RPCHEADER)
	$(CC) $(CFLAGS) -o $@ $^

sync_vault_client: sync_vault_clnt.o sync_vault_client_custom.o $(RPCHEADER)
	$(CC) $(CFLAGS) -o $@ $^

sync_vault_client_auto: sync_vault_clnt.o  sync_vault_client.o
	$(CC) $(CFLAGS) -o $@ $^

build: $(RPCHEADER) $(EXES) 

clean::
	rm -rf $(EXES) $(RPCCLIENT) $(RPCGENERATED) *.o
