
RPCGENERATED = sync_vault_clnt.c  sync_vault.h  sync_vault_svc.c 
RPCCLIENT = sync_vault_client.c
RCPSERVER = sync_vault_server.c
EXES = sync_vault_client sync_vault_server

CFLAGS =  -DSERVICE_NAME=\"sync_vault_server\"
CFLAGS += -I /usr/include/tirpc -ltirpc -std=c99

default: build

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Generate the auto-created files
$(RPCGENERATED): sync_vault.x
	rpcgen -N $^
	#sed -i sync_vault.h -e 's/sync_vault_ping_1_svc(int/sync_vault_ping_1_svc(int*/'

# Client main is also autogenerated
$(RPCCLIENT): sync_vault.x sync_vault.h
	rpcgen -Sc -N -o $@ $<

sync_vault_server: sync_vault_svc.o sync_vault_server.o 
	$(CC) $(CFLAGS) -o $@ $^

sync_vault_client: sync_vault_clnt.o  sync_vault_client_custom.o
	$(CC) $(CFLAGS) -o $@ $^

sync_vault_client_auto: sync_vault_clnt.o  sync_vault_client.o
	$(CC) $(CFLAGS) -o $@ $^

build: $(EXES) 

clean::
	rm -rf $(EXES) $(RPCCLIENT) $(RPCGENERATED) *.o
