/*
 * This is started as sample code generated by rpcgen.
 * via rpcgen -Ss -N sync_vault.x
 * The guts of the sync_vault_ping_1 function is then specific to our use case

 * Operation:
 *      Client makes a request for the sync_vault_ping service
 *          - The request MUST come from a privileged ( < 1024 ) port, else
 *            server will ignore
 *      Server
 *          - validates request originated from port < 1024
 *          - Invokes a script (SCRIPTPATH) relative the directoryl; 
 */

#include "sync_vault.h"

#include <stdlib.h>
#include <unistd.h>
#include <assert.h>

#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <signal.h>

#include <netinet/in.h>
#include <netdb.h>

#include <syslog.h>
#include <limits.h>
#include <stdio.h>

/* ####  Replace the name of the script and recompile ##### */
#define SCRIPT "catarg.sh"

int *
sync_vault_ping_1_svc(int arg, struct svc_req *rqstp)
{
	static int  result;
        struct netbuf *caller;
	char *ipaddr;
	int status;
	int pid;
        int sender_port;
        char sendp[128];

        
	switch(pid = fork()){
		case -1:		/*Fork failed*/
			result = -1;
			return &result;

		case 0:			/* Child */
			break;
		default:		/* Parent */
			result = 0;
			return &result;
	}
	
        caller = svc_getrpccaller(rqstp->rq_xprt);
       
        if (caller->len == INET_ADDRSTRLEN)
        {
            struct sockaddr_in *addr = (struct sockaddr_in *) caller->buf; 
	    ipaddr = (char *)malloc(sizeof(char)*INET_ADDRSTRLEN);
            inet_ntop(AF_INET, &addr->sin_addr, ipaddr, INET_ADDRSTRLEN);
            sender_port = ntohs(addr->sin_port);
	    fprintf(stderr, "Received request from addr %s port %d\n", ipaddr, sender_port);
        }
        else if (caller->len == INET6_ADDRSTRLEN)
        {
            struct sockaddr_in6 *addr = (struct sockaddr_in6 *) caller->buf; 
	    ipaddr = (char *)malloc(sizeof(char)*INET6_ADDRSTRLEN);
            inet_ntop(AF_INET6, &addr->sin6_addr, ipaddr, INET6_ADDRSTRLEN);
            sender_port = ntohs(addr->sin6_port);
	    fprintf(stderr, "Received request from addr %s port %d\n", ipaddr, sender_port);
        }
        else
            ipaddr = NULL;


        if (ipaddr != NULL && sender_port < 1024)
        {
	        syslog(LOG_DEBUG, "Received request from  %s", ipaddr);
	        fprintf(stderr, "Received request from %s\n", ipaddr);
                sprintf(sendp,"%d",sender_port);
		status = execl(SCRIPT, ipaddr, sendp, NULL);
        }
        else
             status = -1;
        if (sender_port >= 1024)
        {
	     fprintf(stderr, "request from unprivileged remote user (port: %d)\n",sender_port);
             status = - sender_port;
        }

	fprintf(stderr, "execl status %d\n",status);
	exit(status);
}

